FLASH_DEF = 1M256
CPP_EXTRA = -Wall -DLED_PIN=2
#CPP_EXTRA = -Wall -DLED_PIN=2 -O0 -DDEBUG_ESP_WIFI -DDEBUG_ESP_PORT=Serial
BUILD_EXTRA_FLAGS = "-DMQTT_MAX_PACKET_SIZE=1152"
USER_LIBS = ${HOME}/Arduino/libraries/
